version: '3'
services:
  postgres-db:
    image: postgres
    hostname: postgres-db
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - db_network
  api_app:
    hostname: api_app
    container_name: api_app
    build:
      context: ./api
      dockerfile: ./Dockerfile
    environment:
      PORT: 8081
      DB: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}"
      DB_HOST: postgres-db
      DB_USER: ${POSTGRES_USER}
      DB_DATABASE: ${POSTGRES_DB}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: 5432
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db
    networks:
      - db_network
      - web_network
  web:
    hostname: web_app
    container_name: web_app
    build:
      context: ./web
      dockerfile: /Dockerfile
    environment:
      PORT: 8080
      API_HOST: http://api_app:8081
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - api_app
    networks:
      - web_network
networks:
  db_network:
  web_network: